### PR TITLE
Implementation of RuLSIF

### PR DESCRIPTION
**Pull request by ameya98**
Computes the alpha-relative density-ratio via RuLSIF, a modification to uLSIF. (When alpha is 0, these are identical).
Further, contains an implementation of the alpha-relative KL-divergence and alpha-relative PE-divergence approximators for the computed density-ratio approximator.

Reference:
Change-Point Detection in Time-Series Data by Relative Density-Ratio Estimation
Song Liu, Makoto Yamada, Nigel Collier and Masashi Sugiyama
https://arxiv.org/pdf/1203.0453.pdf

### CODE REVIEW

**Comment by ameya98** [comment]
Added some more tests as well - plots in test_advanced.

**Comment by ameya98** [comment]
Also, I fixed the issue with sigma_range and lambda_range defaults. Previously, they did not span from 1e-3 to 1e9, while the function docstring claimed they did.

**Comment by hoxo-m** [comment]
It is a great job!

**Comment by hoxo-m** [comment]
I think you should be added as an author because you made a big contribution.

**Comment by ameya98** [comment]
Sure, that would be amazing! I'm Ameya Daigavane. Thank you so much!

**Comment by ameya98** [comment]
The documentation also needs to be changed slightly to reflect these changes. I will get to that soon.

**Comment by ameya98** [comment]
Documentation changes are done, see my other PR. Thanks!

**Pull request merged**
